/**
 * Seeded generator, so anything built on top of sampling is reproducible.
 *
 * The solver and the equity matrix are committed artefacts. If they could not
 * be regenerated byte for byte, "these numbers were computed" would be a claim
 * nobody could check, including me.
 */
export function mulberry32(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
