/**
 * Solve the turn for every scenario, and ship the turn nodes only.
 *
 *     npx vite-node scripts/solve-turn-spots.ts
 *     -> src/lib/charts/turn.generated.ts
 *
 * A turn solve is eight seconds and twenty megabytes, so it happens here rather
 * than in a browser tab, the same way the push/fold charts do.
 *
 * What gets written is only the FOUR turn nodes, not the five hundred and
 * seventy six river ones underneath them. Forty eight rivers are solved to get
 * the turn right, and forty seven of them never happen; shipping them all would
 * be megabytes so that one could be read. `playthrough.ts` solves the river
 * that actually comes, live, from the ranges the turn action leaves behind.
 */

import { writeFileSync } from "node:fs";
import { solve } from "../src/lib/solver/cfr";
import { evaluateDecision } from "../src/lib/solver/evaluate";
import { SPOTS, buildSpot } from "../src/lib/postflop/spots";
import { packTurnNode, type PackedTurn } from "../src/lib/postflop/turn-data";
import { countNodes } from "../src/lib/solver/tree";

const ITERATIONS = 200;

console.log(`Solving ${SPOTS.length} turn scenarios at ${ITERATIONS} iterations.\n`);

const packed: PackedTurn[] = SPOTS.map((definition) => {
  const spot = buildSpot(definition);
  const nodes = countNodes(spot.tree);
  process.stdout.write(
    `  ${definition.id.padEnd(16)} ${spot.hands.count} hands, ${nodes.player} nodes ... `,
  );

  const started = Date.now();
  const solution = solve(spot.tree, spot.hands, spot.ranges, {
    iterations: ITERATIONS,
    views: spot.views,
  });
  const average = spot.tree.playerNodes.map((node) => solution.strategyAt(node));
  const turnNodes = spot.tree.playerNodes.filter((node) => node.street === 0);

  const entry: PackedTurn = {
    spotId: definition.id,
    handCount: spot.hands.count,
    exploitabilityPercent: solution.exploitabilityPercent,
    nodes: turnNodes.map((node) => {
      // Expected values are what scores your decisions, so they are only needed
      // where you are the one deciding. At the opponent's nodes the frequencies
      // are the whole story, and skipping the values halves the file.
      const values =
        node.player === definition.hero
          ? evaluateDecision(spot.tree, spot.hands, spot.ranges, average, node, spot.views).values
          : null;
      return packTurnNode(node.id, average[node.id]!, values);
    }),
  };

  console.log(
    `${((Date.now() - started) / 1000).toFixed(1)}s, ` +
      `${turnNodes.length} turn nodes, ${solution.exploitabilityPercent.toFixed(3)}% of pot`,
  );
  return entry;
});

const body = `/**
 * GENERATED by scripts/solve-turn-spots.ts. Do not edit.
 *
 * The turn strategy for each scenario: what each player does with every hand,
 * plus the expected value of each action at the nodes you decide at. Solved at
 * ${ITERATIONS} iterations; the exploitability each one reached is on the entry
 * and the screen shows it, because a solved number that does not say how solved
 * it is has the same standing as a chart somebody typed.
 *
 * The river is deliberately absent. See turn-data.ts.
 */

import type { PackedTurn } from "../postflop/turn-data";

export const TURNS: readonly PackedTurn[] = ${JSON.stringify(packed, null, 2)};

export const TURNS_BY_SPOT: ReadonlyMap<string, PackedTurn> = new Map(
  TURNS.map((turn) => [turn.spotId, turn]),
);
`;

writeFileSync("src/lib/charts/turn.generated.ts", body);
console.log(`\nWrote src/lib/charts/turn.generated.ts (${(body.length / 1024).toFixed(0)} kB)`);
