/**
 * Solve every scenario from the flop, and ship the flop nodes only.
 *
 *     node --max-old-space-size=8192 ./node_modules/.bin/vite-node scripts/solve-flops.ts
 *     -> src/lib/charts/flop.generated.ts
 *
 * Optionally narrowed to one scenario, which is how six of these get run at
 * once across cores rather than one after another for an hour and a half:
 *
 *     ... scripts/solve-flops.ts bb-defends-two-tone
 *     -> src/lib/charts/flop.bb-defends-two-tone.json
 *
 * With no argument it collects whatever per-scenario JSON is already on disk,
 * solving only what is missing, and writes the generated module.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { SCENARIOS, buildFlopGame } from "../src/lib/postflop/scenario";
import { solveFlop } from "../src/lib/postflop/flop-solve";
import { flopNodesByPath, packFlopNode, type PackedFlop } from "../src/lib/postflop/flop-data";
import { countNodes } from "../src/lib/solver/tree";

const ITERATIONS = Number(process.env.FLOP_ITERATIONS ?? 160);
const BUCKETS = Number(process.env.FLOP_BUCKETS ?? 16);

const partOf = (id: string) => `src/lib/charts/flop.${id}.json`;

function solveOne(id: string): PackedFlop {
  const scenario = SCENARIOS.find((entry) => entry.id === id);
  if (!scenario) throw new Error(`No scenario called ${id}`);

  const started = Date.now();
  const game = buildFlopGame(scenario);
  const nodes = countNodes(game.tree);
  console.log(
    `${id}: ${game.hands.count} hands, ${nodes.player} decision nodes, ` +
      `${ITERATIONS} iterations, river in ${BUCKETS} buckets`,
  );

  const solved = solveFlop(game, {
    iterations: ITERATIONS,
    buckets: BUCKETS,
    onProgress: (iteration) => {
      const minutes = (Date.now() - started) / 60000;
      console.log(
        `  ${id} ${String(iteration).padStart(4)}/${ITERATIONS}  ` +
          `${minutes.toFixed(1)}m elapsed, ~${((minutes / iteration) * (ITERATIONS - iteration)).toFixed(1)}m left`,
      );
    },
  });

  const byPath = flopNodesByPath(game.tree);
  const packed: PackedFlop = {
    scenarioId: id,
    handCount: game.hands.count,
    exploitabilityPercent: solved.exploitabilityPercent,
    iterations: ITERATIONS,
    riverBuckets: BUCKETS,
    nodes: [...byPath].map(([path, node]) => {
      const strategy = solved.strategies.get(node.id)!;
      // Values price your decisions, so they are only needed where you decide.
      const ev = node.player === game.seats.hero ? strategy.ev : null;
      return packFlopNode(path, strategy.frequency, ev);
    }),
  };

  console.log(
    `  ${id} done in ${((Date.now() - started) / 60000).toFixed(1)}m, ` +
      `${packed.nodes.length} flop nodes, ${solved.exploitabilityPercent.toFixed(3)}% of pot`,
  );
  return packed;
}

const only = process.argv[2];
if (only) {
  writeFileSync(partOf(only), JSON.stringify(solveOne(only)));
  console.log(`Wrote ${partOf(only)}`);
} else {
  const packed = SCENARIOS.map((scenario) => {
    const path = partOf(scenario.id);
    if (existsSync(path)) {
      console.log(`${scenario.id}: reusing ${path}`);
      return JSON.parse(readFileSync(path, "utf8")) as PackedFlop;
    }
    const solved = solveOne(scenario.id);
    writeFileSync(path, JSON.stringify(solved));
    return solved;
  });

  const worst = Math.max(...packed.map((entry) => entry.exploitabilityPercent));
  const body = `/**
 * GENERATED by scripts/solve-flops.ts. Do not edit.
 *
 * The flop strategy for each scenario: what each player does with every hand,
 * plus the expected value of each action at the nodes you decide at. Solved
 * over three streets -- flop, all 49 turns, all 48 rivers under each -- at
 * ${ITERATIONS} iterations with the river grouped into ${BUCKETS} buckets, which is what
 * makes 85,264 decision nodes fit in memory.
 *
 * The worst of these reached ${worst.toFixed(3)}% of pot, measured in the full game with the
 * best response free to punish whatever the bucketing gave away. The screen
 * shows that number, because a solved number that does not say how solved it is
 * has the same standing as a chart somebody typed.
 *
 * The turn and river nodes are deliberately absent. See flop-data.ts.
 */

import type { PackedFlop } from "../postflop/flop-data";

export const FLOPS: readonly PackedFlop[] = ${JSON.stringify(packed, null, 2)};

export const FLOPS_BY_SCENARIO: ReadonlyMap<string, PackedFlop> = new Map(
  FLOPS.map((flop) => [flop.scenarioId, flop]),
);
`;

  writeFileSync("src/lib/charts/flop.generated.ts", body);
  console.log(`\nWrote src/lib/charts/flop.generated.ts (${(body.length / 1024).toFixed(0)} kB)`);
}
