/**
 * Solve the turn spots offline and write them out as data.
 *
 *     npx vite-node scripts/solve-turn-spots.ts
 *     -> src/lib/charts/turn.generated.ts
 *
 * A turn solve is eight seconds and twenty megabytes, and nobody waits eight
 * seconds between hands. So the same thing happens here that already happens
 * for push/fold: solve it once, commit the answer, and let the drill load it
 * instantly. River spots are a few hundred milliseconds and are solved in the
 * browser instead, which is why they are not in this file.
 *
 * The cost of the trade is honest and worth stating: you drill the turn spots
 * that were precomputed, not any turn spot you can imagine. Making arbitrary
 * turn spots solvable while you wait is depth-limited solving, which is the
 * next phase in docs/postflop-solver.md.
 */

import { writeFileSync } from "node:fs";
import { packDecision, solveDecision } from "../src/lib/postflop/decision";
import { SPOTS, buildSpot } from "../src/lib/postflop/spots";
import { countNodes } from "../src/lib/solver/tree";

const ITERATIONS = 200;
const turnSpots = SPOTS.filter((spot) => spot.street === "turn");

console.log(`Solving ${turnSpots.length} turn spots at ${ITERATIONS} iterations.\n`);

const packed = turnSpots.map((definition) => {
  const built = buildSpot(definition);
  const nodes = countNodes(built.tree);
  process.stdout.write(
    `  ${definition.id.padEnd(18)} ${built.hands.count} hands, ` +
      `${nodes.player} nodes, ${nodes.chance} chance ... `,
  );

  const started = Date.now();
  const decision = solveDecision(built, { iterations: ITERATIONS });
  const elapsed = Date.now() - started;

  console.log(
    `${(elapsed / 1000).toFixed(1)}s, ${decision.hands.length} hands reach it, ` +
      `${decision.exploitabilityPercent.toFixed(3)}% of pot`,
  );
  return packDecision(decision);
});

const body = `/**
 * GENERATED by scripts/solve-turn-spots.ts. Do not edit.
 *
 * Turn spots, solved. Each entry is the strategy and the expected value of
 * every action, for every hand that can actually arrive at the decision.
 * Frequencies are one byte each and expected values two, scaled to the range
 * the spot spans; see packDecision for why those widths.
 *
 * Solved at ${ITERATIONS} iterations. The exploitability each one reached is on
 * the entry, and the drill screen shows it, because a solved number that does
 * not say how solved it is has the same standing as a chart somebody typed.
 */

import type { PackedDecision } from "../postflop/decision";

export const TURN_DECISIONS: readonly PackedDecision[] = ${JSON.stringify(packed, null, 2)};

export const TURN_DECISIONS_BY_SPOT: ReadonlyMap<string, PackedDecision> = new Map(
  TURN_DECISIONS.map((decision) => [decision.spotId, decision]),
);
`;

writeFileSync("src/lib/charts/turn.generated.ts", body);
console.log(`\nWrote src/lib/charts/turn.generated.ts (${(body.length / 1024).toFixed(1)} kB)`);
